### ISSUE TITLE
Discussion: Project Status Codelist

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#10] opened 2018-09-23 21:51 UTC
In the current version of the project level schema, `phase` is an open codelist with the following codes:

* identification
* preparation
* construction
* completion

This differs from the project phases defined in [CoST guidance note 6](http://infrastructuretransparency.org/wp-content/uploads/2011/12/31_CoST_Guidance_Note_6_Proof.pdf) which uses 'implementation' rather than 'construction'.

The description of the implementation stage in the CoST guidance note covers the procurement and implementation of *planning* and *design* (as well as construction) contracts.

**Proposal:**

Align the codes and descriptions in the `phase` codelist with those in CoST guidance note 6:

Code | Description
------------ | -------------
identification | the decision to develop a project within the budget and programme of a project owner, which will be the public entity responsible for executing the budget
preparation | the feasibility study, environmental and social impact assessment, general scoping of the project, establishing the packaging and procurement strategy, preliminary statutory requirements on environmental and land impacts, and the resulting budget authorisation
implementation | the procurement and implementation of the planning, design and works according to the procurement strategy
completion | the handover of the assets and close-out activities with details of the final scope, cost and delivery time

**Discussion:**

* Can these definitions be clarified or improved? e.g. could the definition of 'implementation' include mention of supervision contracts
* How much of an issue is the difference in meaning between 'implementation' as a phase at the project level in the CoST IDS and 'implementation' as a stage of the contracting process in OCDS?

**Comment by jpmckinney** [comment] 2018-09-24 02:32
I read five phases in guidance note 6:

1. **Project identification** refers to the decision to develop a project within the budget and programme of a project owner, which will be the public entity responsible for executing the budget.
1. **Project preparation** covers the feasibility study, environmental and social impact assessment, general scoping of the project, establishing the packaging and procurement strategy, preliminary statutory requirements on environmental and land impacts, and the resulting budget authorisation.
1. Project **completion** covers the handover of the assets and close-out activities with details of the final scope, cost, and delivery time.
1. **Procurement** is the process for selecting different services (design, supervision and or construction etc.) to deliver the project. It runs alongside the project cycle as it can occur at a number of different points.
1. **Implementation** or **package delivery** covers the procurement and implementation of the planning, design and works according to the procurement strategy.

(emphasis as in original)

The proposed descriptions are identical.

The proposed codes are similar, dropping the word 'project' as it is redundant. Although the guidance note lists 'procurement' as a phase "within the construction project cycle", it also defines it as running "alongside the project cycle".  Given that the concept note lacks conceptual clarity for its inclusion as a phase *within* a project cycle, I agree with leaving it out of the codelist.

I don't know what 'package delivery' means, but noting that it's not referred to in the proposal in case it's relevant.

For context, in OCDS:

* `Contract.implementation`: "Information related to the implementation of the contract in accordance with the obligations laid out therein."
* `Implementation`: "Information during the performance / implementation stage of the contract."
* `releaseTag.csv` 'implementation' code: "Providing new information on the implementation of a contracting process."

> How much of an issue is the difference in meaning between 'implementation' as a phase at the project level in the CoST IDS and 'implementation' as a stage of the contracting process in OCDS?

Is there a difference in meaning? The descriptions in OCDS are sufficiently vague, that they can mean the same thing as implementation in CoST IDS.

**Comment by duncandewhurst** [comment] 2018-09-24 02:44
thanks @jpmckinney 

> I don't know what 'package delivery' means, but noting that it's not referred to in the proposal in case it's relevant.

Ah, well spotted, the omission wasn't intentional, the CoST guidance note states:

![image](https://user-images.githubusercontent.com/19265814/45936175-e9477800-bf89-11e8-9308-f85bc519ec2b.png)

We can explore in the consultation at data standards day whether it is important to include that in the description of the implementation code.

> Is there a difference in meaning? The descriptions in OCDS are sufficiently vague, that they can mean the same thing as implementation in CoST IDS.

Simply that in CoST implementation 'covers the procurement and implementation of the planning, design and works according to the procurement strategy' which I took to mean that in addition to activities post the signature of the contract (i.e. the implementation stage in OCDS terms), it also covers tender, award and contract stages of a the procurement, which in OCDS are distinct from implementation.

**Comment by jpmckinney** [comment] 2018-09-24 02:49
Indeed, 'the procurement' in the description of 'implementation' suggests it covers tender, etc. However, given that CoST lists 'procurement' as a separate phase, I wonder whether it's a typo, as it wouldn't make sense for a phase to include another phase. I'd prefer a definition of 'implementation' that omitted 'the procurement and' – though this may need to be validated with CoST and stakeholders.

**Comment by jpmckinney** [comment] 2018-09-24 02:55
In the draft guidance note 9, this field is named 'Project status (current)' and described as "The current stage of the project. Select from identification, preparation, construction or completed"

'completed' has different semantics than 'completion'. The latter can mean 'in the process of completion' or 'in the final stages of completion'. I take guidance note 6 as having the intended semantics, i.e. 'completion' is appropriate.

**Comment by timgdavies** [comment] 2018-10-09 15:14
I've staged updates here https://github.com/open-contracting/infrastructure/commit/f19f5e1eabf0a1fe436a0cac35e18c5a95bef81d which consolidate project phase  and status into one list consisting of:

| Code           | Title          | Description                                                                                                                                                                                                                                                                                | 
|----------------|----------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------| 
| identification | Identification | Identification refers to the decision to develop a project within the budget and programme of a project owner (the public entity responsible for executing the budget).                                                                                                                    | 
| preparation    | Preparation    | "Preparation covers the feasibility study, environmental and social impact assessment, general scoping of the project, establishing the packaging and procurement strategy, preliminary statutory requirements on environmental and land impacts, and the resulting budget authorisation." | 
| construction   | construction   | "Implementation or package delivery covers the procurement and implementation of the planning, design and works according to the procurement strategy."                                                                                                                                    | 
| completion     | Completion     | "Completion covers the handover of the assets and close-out activities with details of the final scope, cost, and delivery time."                                                                                                                                                          | 
| completed      | Completed      | "Close-out activities have been completed, and this project is no longer active. This project may be displayed as part of a list of archived projects."                                                                                                                                    | 
| cancelled      | Cancelled      | "This project has been cancelled prior to close-out activities. Cancellation may have taken place at any point after identification."                                                                                                                                                      | 

In this list, we have 'construction' rather than 'implementation' and this covers procurement *and* construction. By avoiding the term 'implementation', we are able to escape comparisons to the OCDS 'implementation' phase (although there is no reason we should think the project implementation/construction phase needs to be coterminous with the contract's construction/implementation phase).

**Comment by timgdavies** [comment] 2018-10-10 10:34
> Are the descriptions for 'completed' and 'cancelled' sourced (or based on) an external document? 

The definitions were not taken from an external document.

Given time constraints - I'm moving this issue to beta, so that the final definition of codelist entries can be agreed after discussion with CoST

**Comment by duncandewhurst** [comment] 2018-11-07 15:33
I've made the updates to code descriptions proposed by @jpmckinney on [this branch](https://github.com/open-contracting/infrastructure/tree/10-projectStatus-updates)

I think the only outstanding question in this issue is naming the following code:

Code | Title | Description
---|---|---
construction | Construction | Project implementation covers the procurement and implementation of the group of works or services to be delivered under the project, including works or services performed by the procuring entity.

@EvelynDinora - for the implementation phase in CoST, which includes both procurement and implementation of related contracts, we have proposed instead using the term 'construction', to avoid confusion with the implementation stage in OCDS, which is distinct from the procurement of a contract. Could you confirm:

1. Is 'construction' is an appropriate synonym for 'implementation' in this context (i.e. would all infrastructure projects include some form of physical construction in the implementation phase)?

2. If not, is there another synonym we could use here to avoid the clash with 'implementation' in OCDS?

If the answer to both of the above questions is no, then we can revert to using 'implementation' and I'll draft updates to descriptions and guidance to mitigate the potential for confusion.

**Comment by EvelynDinora** [comment] 2018-11-28 09:41
We prefer maintain the 5 phases described in Note 6: Project identification, Project preparation, Procurement [_is the process for selecting different services (design, supervision and or construction etc.) to deliver the project. It runs alongside the project cycle as it can occur at a number of different points]_, Implementation and Project Completion. 

We need to modified the description of Implementation as it covers the implementation of the  design, supervision and works contracts according to the planning and preparation phase. 

Regarding to your questions: 

Is 'construction' an appropriate synonym for 'implementation' in this context (i.e. would all infrastructure projects include some form of physical construction in the implementation phase)? Not necessarily, sometimes the supervision firm starts the implementation phase by drafting a report on the design prior construction starts. But, yes all infrastructure projects will include at some point physical construction. 

If not, is there another synonym we could use here to avoid the clash with 'implementation' in OCDS?
I think modifying the description of the phase will be enough since I understand implementation in the OCDS refers to contract implementation and in this way we align the concepts. If is necessary to change the word I think that "Delivery" it might be the best synonym.

**Comment by duncandewhurst** [comment] 2018-11-29 11:48
> We prefer maintain the 5 phases described in Note 6: Project identification, Project preparation, Procurement [is the process for selecting different services (design, supervision and or construction etc.) to deliver the project. It runs alongside the project cycle as it can occur at a number of different points], Implementation and Project Completion.

Procurement was omitted from the codelist since it can run alongside different phases of the project as reflected in the draft definition for project status in Guidance Note 9 where it is also omitted:

> The current stage of the project.  Select from identification, preparation, construction or completed

The diagram in Guidance Note 6 also shows procurement as distinct from (and overlapping) the phases of the project.

![image](https://user-images.githubusercontent.com/19265814/49219780-33a30600-f3cc-11e8-9370-434380d1173f.png)

The 'completed' and 'cancelled' codes were added based on experience from OCDS which has shown that identifying when a project is completed (rather than being in the process of completion) or cancelled (rather than successfully completed) is important to users (see https://github.com/open-contracting/infrastructure/issues/14)

> We need to modified the description of Implementation as it covers the implementation of the design, supervision and works contracts according to the planning and preparation phase.

Taking into account the above and the use of 'delivery' rather than 'construction' or 'implementation', please see the updated description below:

Code | Title | Description
---|---|---
delivery | Delivery | Project implementation covers the procurement and implementation of the group of services, such as design and supervision, or works to be delivered under the project, including works or services performed by the procuring entity.

**Comment by Manu2510** [comment] 2019-01-15 00:56
Hi Everyone,  in terms of **delivery** we should consider that in many countries the formal document for the handover of the assets is an Acceptance Note or Delivery Certificate  (in Spanish Recibido Conforme or Acta de Entrega).

**Comment by EvelynDinora** [comment] 2019-01-28 08:10
What is commented by Manuel is what we all CoST working group agreed. That is a definition understood by our members.

**Comment by duncandewhurst** [comment] 2019-01-29 16:39
@Manu2510 @EvelynDinora please clarify your proposal.

Do you mean we should revert to using 'implementation' instead of 'delivery' for this project stage?

**Comment by cost-platform** [comment] 2019-02-27 09:17
Yes, please. We double check with the working group and delivery is understood as the handover of the asset. So, implementation should be the proper terminology to use.

**Comment by jpmckinney** [comment] 2019-02-27 13:46
"implementation" is fine with me – we can distinguish it from the concept in OCDS though the definition.

**Comment by aguilerapy** [comment] 2021-09-22 16:18
From [project status codelist](https://standard.open-contracting.org/infrastructure/0.9/en/reference/codelists/#projectstatus), right now 'implementation' may cover multiple things:

> Implementation covers the procurement and implementation of the group of works or services (such as design and supervision) to be delivered under the project, including works or services performed by the procuring entity.

I had a meeting with Mexico INAI (see [CRM 7623](https://crm.open-contracting.org/issues/7623)) where @antonioherrera and @ElioenaiVazquez explained that it seems to him that the 'implementation' status can be further disaggregated. Said that we have two states before implementation ('identification' and 'preparation') and two after ('completion' and 'completed'), but only one for the actual implementation (the more important phase). Currently, 'implementation' may reflect the process of procurement, awarded, design,  construction, commissioning, maintenance, and/or all the other works or services performed.

The question is about the possibility of adding more codes, knowing that right now we are following the CoST recommendations. Alternatively, to know if it's possible to add a new field that gives us more information about the implementation stage, mainly because at this stage a project can evolve and remain for a long time.

**Comment by jpmckinney** [comment] 2021-09-22 16:52
I think procurement, award, design, etc. are more appropriate statuses/natures for individual contracting processes. In a big project, you very likely have multiple contracts each with different statuses (some being procured, some already awarded). In that case, it does not make sense for the project status to be procurement, awarded, etc., which is why we left it as just 'implementation'.

**Comment by yolile** [comment] 2021-09-22 17:09
I think that, based on the call notes, the issue is when the project has different contracting processes eg one for the public work design, then another one for the construction itself, and then another one for the supervision, etc. In either of that stages, the project status will be "implementation" but then, the user will need to look up the contracting processes to know at what specific stage of the implementation the work is, if it is already being constructed or designed, etc

**Comment by yolile** [comment] 2021-09-22 17:16
Note that design, construction, and supervision are [contract natures](https://standard.open-contracting.org/infrastructure/0.9/en/reference/codelists/#contractnature). So, the user needs to look up the `summary` block to know exactly at which stage of the implementation the project is.

**Comment by jpmckinney** [comment] 2021-09-22 18:09
Yes, but I think that work by the user is necessary. A project to build an underpass might require the reinforcement of the above-ground train track (construction) while also requiring the design of the underground mall (design), before proceeding to the digging of the underpass (construction) – all of which is supervised – so there is no singular value we can put at the project-level that will make sense, except 'implementation'.

For simple projects that have very linear status updates, it's maybe possible to have a more granular project-level status – but then simple projects have very few contracts (maybe just one?), such that it's just as easy to check the contract instead.

**Comment by aguilerapy** [comment] 2021-09-22 18:10
Yes, It makes sense. So if we want to know the status of the implementation of the project we must go to review the nature of each contract related to the project, then:

- If there are only contracts with the code 'design' in the `nature` array and the project `status` is 'implementation', then the project is in the design stage.
- If there are contracts with the code 'construction' in the `nature` array and the project `status` is 'implementation', then the project is in the construction stage (but if previously the project went through design and construction, we should also check the dates).
- If there are contracts with the code 'design' and 'construction' in the `nature` array, is more difficult to know exactly which of the two stages the project is in.

Is that right? I didn't add 'supervision', because I think it can overlap with 'construction'.

Also, I think we could ask @antonioherrera if they identified some other contract nature in addition to the existing ones.

**Comment by jpmckinney** [comment] 2021-09-22 18:13
Yes, I think the analysis needs to be performed by the user (like in your example), since different users/applications might summarize the project's status in different ways, based on the contract statuses and natures.

**Comment by yolile** [comment] 2021-09-22 18:16
Agree. The only issue is when the OC4IDS publisher doesn't publish the `summary` block at all and only the `releases` array (as Nuevo Leon currently does), as we don't have a `Contract.nature` field in OCDS.

**Comment by duncandewhurst** [comment] 2021-11-24 02:56
Can this issue be closed?

**Comment by jpmckinney** [comment] 2021-11-24 03:03
It seems like there is agreement - though as @yolile points out sometimes incomplete data will make determining the project status somewhat more difficult. That said, I think the solution is to add in an additional field like `Contract.nature` to OCDS, rather than set a project status.

**Closed by jpmckinney** 2021-11-24 03:03 UTC
Labels: codelists
