### ISSUE TITLE
Add a field to indicate whether a project includes government support

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#250] opened 2020-12-21 02:44 UTC
SIF's SOURCE platform includes a boolean `Government support` field to indicate whether the project includes [government support](https://ppp.worldbank.org/public-private-partnership/financing/government-support-subsidies)

**Comment by jpmckinney** [comment] 2020-12-21 03:29
We could maybe have a mostly empty finance object to indicate the government support, but without additional details, following the same model as OCDS: https://extensions.open-contracting.org/en/extensions/finance/master/schema/

**Comment by duncandewhurst** [comment] 2020-12-21 21:46
Could you sketch a JSON example of what you mean?

**Comment by jpmckinney** [comment] 2020-12-21 22:22
The [OCDS for EU](https://standard.open-contracting.org/profiles/eu/master/en/forms/F01/#/OBJECT_CONTRACT/OBJECT_DESCR/EU_PROGR_RELATED) extension uses a Finance object to indicate the financingParty and a description. Here, the financingParty could be similarly set. This allows for future details to be added at an appropriate location.

**Comment by duncandewhurst** [comment] 2021-03-16 01:13
Adding an example, based on SOURCE's data:

```json
{
  "projects": [
    {
      "parties": [
        {
          "id": "1",
          "name": "Ministry of Finance"
        }
      ],
      "budget": {
        "finance": [
          {
            "id": "1",
            "description": "Government Support",
            "financingParty": {
              "id": "1",
              "name": "Ministry of Finance"
            }
          }
        ]
      }
    }
  ]
}
```

**Comment by jpmckinney** [comment] 2023-12-07 23:14
The issue is to add a field, and the new Finance fields make this possible. I'm not sure that we need to add an example, so closing. We can open a new issue if an example is desired.

**Closed as completed by jpmckinney** 2023-12-07 23:14 UTC
Labels: schema, ppp
