### ISSUE TITLE
Copy project and project package schema files to 0__9__0__beta directory

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#113] opened 2019-03-12 16:59 UTC
The project and project package schemas should be available at the following URLs:

http://standard.open-contracting.org/infrastructure/0__9__0__beta/project-schema.json

http://standard.open-contracting.org/infrastructure/0__9__0__beta/project-package-schema.json

The steps to follow are here: https://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/technical/deployment/#copy-the-schema-into-place

**Comment by jpmckinney** [comment] 2019-03-20 22:01
Hmm, both of those URLs 404.

**Comment by kindly** [comment] 2019-06-17 10:38
The issue is the urls should be

http://standard.open-contracting.org/infrastructure/schema/0__9__0__beta/project-schema.json
http://standard.open-contracting.org/infrastructure/schema/0__9__0__beta/project-package-schema.json

i.e they are missing the `/schema` bit in the URL. 

This is needed for the oc4ids cove to work properly as the `id` and the `$ref` are broken.

@jpmckinney do you think we should do a 0_9_1__beta release with this fix and also other changes in dev/pull requests?
These include:
- i18n changes using the new version of ocds-babel
- the changlog pull request when ready

**Comment by jpmckinney** [comment] 2019-06-17 14:25
Works for me! I committed i18n changes directly.

Re: version name, shouldn't it be 0.9.0.beta.2? Either that, or we drop 'beta' and start going with 0.9.1 and up. 0.* series generally indicate an 'in-development' or 'non-stable' status.

**Comment by kindly** [comment] 2019-06-17 15:25
I would just be happy with just 0.9.1 as I do not think we are going to do just a `0.9.0` release which is what the `beta` suggests we are aiming at.

**Comment by kindly** [comment] 2019-06-17 15:48
#137 should fix this.

**Comment by kindly** [comment] 2019-06-18 14:39
Fixed in #137 and deployed.

**Closed by kindly** 2019-06-18 14:39 UTC
Labels: build process
