### ISSUE TITLE
Add numberOfBeneficiaries in planning

### ISSUE THREAD

**Issue by SecretariaInfraestructuraNL** [open-contracting/infrastructure#335] opened 2021-07-09 20:53 UTC
The state of Nuevo León, in Mexico, publishes information on its public works contracts through the open infrastructure platform and json files.

[PIA](http://si.nl.gob.mx/transparencia/)

One of the important data that it currently publishes is the number of beneficiaries, which is currently published as an extra data from the standard.

For the importance of the data, we consider that the data should be part of the basic planning information at the open contracting Data standard (OCDS)

**Comment by jpmckinney** [comment] 2021-07-09 21:12
Thanks, @SecretariaInfraestructuraNL. Can you describe in more detail what is meant by the number of beneficiaries?

**Comment by duncandewhurst** [comment] 2021-07-11 23:46
@SecretariaInfraestructuraNL - please could you clarify whether the number of beneficiaries relates to the whole infrastructure project, or to an individual contracting process?

There's a related discussion on modelling the beneficiaries of PPP projects here: https://github.com/open-contracting-extensions/public-private-partnerships/issues/235

**Comment by pindec** [comment] 2021-07-15 10:42
Also relevant:
* the [CoST Jalisco statistics page](http://costjalisco.org.mx/statistics) shows total beneficiaries and number of beneficiaries by public authority, and shows [number of beneficiaries by project](http://costjalisco.org.mx/project-single/39) as general information and at the Project Identification stage.
* the [Panama en Obras portal](http://www.panamaenobras.gob.pa/inicio) shows total benefited population, and [each project page](http://www.panamaenobras.gob.pa/inicio/proyecto/3) shows a "benefitted population" number at project level.

**Comment by SecretariaInfraestructuraNL** [comment] 2021-07-16 21:16
Hi @jpmckinney , and thanks to @duncandewhurst  and @pindec  for the recommendations.

I can tell you in Mexico the OCDS standard has been used for some years in order to publish information related to contracts in general. Since this is the standard used in general in the country: We thought to add the field "number of beneficiaries" in the planning section of a contract.

Now day, since we publish specific information about infrastructure projects and their related contracts, and there is a specific standard for this type of information (OC4IDS), it seems to us that the "number of beneficiaries" should appear specified in the "project" file related to the OC4IDS.

In OC4IDS there are no extensions yet, however, we consider that "number of beneficiaries" could be included as part of the basic information, meanwhile, should we add it as and extra field?

**Comment by jpmckinney** [comment] 2021-08-18 00:20
Sorry for the late reply: It is allowed to add additional fields to OC4IDS, even if they are not described by extensions.

**Comment by duncandewhurst** [comment] 2022-08-02 23:31
Looking at the [data](https://smpu.nl.gob.mx/transparencia/publicaciones) from Nuevo León, an additional field (`x_numberOfBeneficiaries`) was added at the project level.

I checked the values of the field for projects in 2021 and it looks like it is being used to disclose the number of people who are expected to benefit from the project:

| x_numberOfBeneficiaries |
| -- |
0
0
4206
4700000
0
4000
944
0
4000
971
0
5784000

Since the data has been added as an additional field, I'm going to close this issue pending further demand.

**Comment by duncandewhurst** [comment] 2023-07-25 23:17
CoST proposed the number of beneficiaries as a new disclosure requirement with the following description:

> Indicate the number of direct and indirect project beneficiaries (E.g. direct: [number]; indirect: “number”). Beneficiaries are those who benefit directly or indirectly from the project; they are the target group of the infrastructure project and their needs are addressed by the intervention. If the information was not used during project appraisal, select the option “data not considered in project appraisal”.

Assuming that this is the number of individual people who benefit from the project (to be confirmed), this could be modelled by adding a `numberOfPeople` field to the structure proposed in https://github.com/open-contracting-extensions/public-private-partnerships/issues/235 (option 3):

```json
{
  "benefits": [
    {
      "id": "1",
      "beneficiaries": [
        {
          "id": "1",
          "description": "Direct beneficiaries",
          "numberOfPeople": 1000
        },
        {
          "id": "2",
          "description": "Indirect beneficiaries",
          "numberOfPeople": 2000
        }
      ]
    }
  ]
}
```

**Comment by jpmckinney** [comment] 2023-07-26 16:43
It looks like CoST wants to estimate both direct and indirect beneficiaries, so there will need to be at least two values (regardless of modelling approach).

Another option is to adopt a more free-form model, like `measures` in the [budget and spending classification](https://extensions.open-contracting.org/en/extensions/budget_and_spend/master/schema/) extension, so that additional measures can easily be added.

**Comment by neelima-j** [comment] 2023-08-15 18:04
* [Example of CoST Jalisco's number of beneficiaries]( http://www.costjalisco.org.mx/project-single/153#:~:text=4%2C500%20people%20benefited )
<img width="681" alt="Screenshot 2023-08-15 at 19 01 11" src="https://github.com/open-contracting/infrastructure/assets/78197684/57b120cb-d3c8-4d84-9631-ed712c90d129">  

* CoST Jalisco's use case appears to be the same as noted in https://github.com/open-contracting/infrastructure/issues/335#issuecomment-880591407

**Comment by odscjen** [comment] 2023-10-19 09:25
Summarising what has already been discussed in light of this proposal being needed to incorporate new data points suggested as part of the 2023 CoST IDS/OC4IDS review:

# Background

This issue relates to the following CoST IDS elements proposed in the CoST IDS/OC4IDS review:

<details>

<summary> Number of beneficiaries </summary> 

## Number of beneficiaries

**Module:** Social
**Indicator:** Beneficiary population 

### Disclosure format

Indicate the number of direct and indirect project beneficiaries (E.g. direct: [number]; indirect: “number”). Beneficiaries are the individuals who benefit directly or indirectly from the project; they are the target group of the infrastructure project and their needs are addressed by the intervention.

(this has been updated from the text quoted in https://github.com/open-contracting/infrastructure/issues/335#issuecomment-1650692507 to make it clear that it is the number of individuals that are being counted.)

</details>

<details>

<summary> Non-climate co-benefits (Preparation) </summary>

## Non-climate co-benefits (Preparation)

**Module:** Climate finance
**Indicator:** Non-climate impact

### Disclosure format

> Identify potential non-climate impacts that have been factored into the project planning. Select from the list: 
> *  economic 
> *  social 
> *  environmental 
> *  gender empowerment 
> [add free text to explain the co-benefits] 

### OC4IDS mapping

> Project level: For each impact identified add a `benefit` object to the `benefits` array and assign it a locally unique `id`. Set the `title` as the list code and add details explaining the benefit to `.description`.

</details>

# Proposal

Create the object proposed in https://github.com/open-contracting-extensions/public-private-partnerships/issues/235 and add an additional field, `numberOfPeople` to the `beneficiaries` object.

Summary of changes

Add the following fields and objects:

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-759a1051-7fff-f2ab-546b-b47afbebd3a4">

Path | Title | Description | Type (format) | Codelist
-- | -- | -- | -- | --
benefits  |  Benefits | The benefits and intended benefits of the project.  | array of Benefit objects |  -
Benefit | Benefit | A benefit or intended benefit of the project. | object | -
Benefit.id | ID | A locally unique identifier for the benefit. | string | -
Benefit.description | Description | A short description of the benefit. | string | -
Benefit.beneficiaries | Beneficiaries | Whom the benefit will aid. | array of Beneficiary objects | -
Beneficiary | Beneficiary | Information about a beneficiary of the project. | object | -
Beneficiary.id | ID | A locally unique identifier for the beneficiary. | string | -
Beneficiary.location | Location | The location of the beneficiary. | `location` object | -
Beneficiary.description | Description | A short description of the beneficiary. | string | -
Beneficiary.numberOfPeople | Number of people | The total size of the beneficiary population. | number | -

</div>

## Example

```json
{
  "benefits": [
    {
      "id": "1",
      "beneficiaries": [
        {
          "id": "1",
          "description": "Direct beneficiaries",
          "numberOfPeople": 1000,
          "location": {}
        },
        {
          "id": "2",
          "description": "Indirect beneficiaries",
          "numberOfPeople": 2000
        }
      ]
    },
    {
      "id": "2",
      "title": "Environmental",
      "description": "The new water management plant will mean less water is removed from the delta meaning more is left in place for use by the local biome."
    }
  ]
}
```

cc @evelyndinora @mgraca-prado

**Comment by duncandewhurst** [comment] 2023-10-31 20:13
I've updated the background and example in https://github.com/open-contracting/infrastructure/issues/335#issuecomment-1770418119 to include the 'non-climate co-benefits' element proposed in the climate finance module. The existing proposal is sufficient to model that element.

**Comment by odscjen** [comment] 2023-11-03 12:36
All proposed fields now have draft descriptions

**Comment by odscjen** [comment] 2023-11-13 12:23
@EvelynDinora, @mgraca-prado, @jpmckinney any comments, clarifications or objections to the proposal in https://github.com/open-contracting/infrastructure/issues/335#issuecomment-1770418119

**Comment by jpmckinney** [comment] 2023-11-13 16:47
Information about who -> whom

Do we need the benefit and beneficiary IDs? I feel like they are unlikely to exist in datasets.

**Comment by odscjen** [comment] 2023-11-14 10:19
I just meant them to be id's that only have meaning within the OC4IDS dataset, similar to an `observation.id`, maybe they're unnecessary though?

**Comment by EvelynDinora** [comment] 2023-11-14 14:53
@odscjen these are 2 diferent elements. One is the number of beneficiaries of the project that we can classify in direct or indirect. 

Another one is the co-benefits of a climate related project beyond mitigation and adpation. The co-benefits could include gender related benefits or economic related  benefits, etc. This a description of co-benefits not necesarly associated directly to the number of beneficiaries.

**Comment by odscjen** [comment] 2023-11-14 15:00
@EvelynDinora what is the change that needs to be made to the proposal? Is it one of the definitions? The model does include 2 different elements, the first is captured b `benefits.beneficiaries` and the second can be captured by `benefits` without including the `.beneficiaries` object. Is it enough to just make that clear in the mapping that the co-benefits are to be a new `Benefit` object and not the same one as the object used for the number of direct or indirect beneficiaries?

**Comment by mgraca-prado** [comment] 2023-11-20 15:03
Hi Jen @odscjen , 
The modelling is indeed capturing the two elements which are:
1. Beneficiaries - number of direct and indirect beneficiaries. 
2.  Co-benefits that are non-climate - explanation of economic, social and/or environmental benefits that the project creates is addition to mitigation and/or adaptation benefits. 
We just need to make clear in the mapping that we are requesting disclosure on both elements.

**Comment by odscjen** [comment] 2023-11-20 17:08
Great, thanks @mgraca-prado we'll make sure and do that.

I'm going to move this to Agreed now, please do move it back if there's still more to discuss

**Closed as completed** 2023-11-28 21:15 UTC
Labels: schema, 2023 oc4ids review
